### ISSUE TITLE
Strange Error

### ISSUE THREAD

**Issue by ScrappyCocco** [edwardslabs/cleverwrap.py#10]
What could cause this error?
It started happening like a day ago and can't understand the cause

```
Ignoring exception in on_message
Traceback (most recent call last):
  File "[...]\Python\Python35\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)

  File "[...]/botLite.py", line 115, in on_message
    reply = cw.say(userMessage)

  File "[...]\Python\Python35\lib\site-packages\cleverwrap\cleverwrap.py", line 61, in say
    self._process_reply(reply)

  File "[...]\Python\Python35\lib\site-packages\cleverwrap\cleverwrap.py", line 83, in _process_reply
    self.count = int(reply.get("interaction_count", None))

ValueError: invalid literal for int() with base 10: ''
```

**Comment by edwardslabs** [comment]
Thanks for reporting this I think I have an idea here but need to do some checking in the morning.

**Comment by edwardslabs** [comment]
I think it is fixed now please upgrade cleverwrap from pypi and let me know if it is still causing issues.

`pip3 install --upgrade cleverwrap`

**Comment by edwardslabs** [comment]
I take your 👍  to mean it is fixed for you also. Feel free to reopen/comment if it is not fixed.
