### ISSUE TITLE
Cleverbot TypeError

### ISSUE THREAD

**Issue by Impulse-PW** [edwardslabs/cleverwrap.py#4]
When using the example code, the following error is thrown:

```
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    cw.say("Hello CleverBot.")
  File "C:\Users\Piero\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cleverwrap\cleverwrap.py", line 61, in say
    self._process_reply(reply)
  File "C:\Users\Piero\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cleverwrap\cleverwrap.py", line 84, in _process_reply
    self.count = int(reply.get("interaction_count", None))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

I'm using python 3, and I've set it to use my api key. Any idea what this is?

**Comment by Impulse-PW** [comment]
Nevermind, it was something I did, I'll close this

**Comment by jamiemclachlan** [comment]
Do you know what you did, because i have this same error.

**Comment by edwardslabs** [comment]
hi @jamiemclachlan there have been a few fixes recently pushed to pypi. Please make sure you have updated to the latest version using `pip install --upgrade cleverwrap`
